# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Dayv2Pub(models.Model):
    houseid = models.CharField(max_length=20)
    personid = models.CharField(max_length=10)
    frsthm = models.CharField(max_length=10)
    outoftwn = models.CharField(max_length=10)
    ontd_p1 = models.CharField(max_length=10)
    ontd_p2 = models.CharField(max_length=10)
    ontd_p3 = models.CharField(max_length=10)
    ontd_p4 = models.CharField(max_length=10)
    ontd_p5 = models.CharField(max_length=10)
    ontd_p6 = models.CharField(max_length=10)
    ontd_p7 = models.CharField(max_length=10)
    ontd_p8 = models.CharField(max_length=10)
    ontd_p9 = models.CharField(max_length=10)
    ontd_p10 = models.CharField(max_length=10)
    ontd_p11 = models.CharField(max_length=10)
    ontd_p12 = models.CharField(max_length=10)
    ontd_p13 = models.CharField(max_length=10)
    ontd_p14 = models.CharField(max_length=10)
    ontd_p15 = models.CharField(max_length=10)
    tdcaseid = models.CharField(primary_key=True, max_length=50)
    hh_hisp = models.CharField(max_length=10)
    hh_race = models.DecimalField(max_digits=65535, decimal_places=65535)
    driver = models.CharField(max_length=10)
    r_sex = models.CharField(max_length=10)
    worker = models.CharField(max_length=10)
    drvrcnt = models.CharField(max_length=10)
    hhfaminc = models.DecimalField(max_digits=65535, decimal_places=65535)
    hhsize = models.CharField(max_length=10)
    hhvehcnt = models.CharField(max_length=10)
    numadlt = models.CharField(max_length=10)
    flag100 = models.CharField(max_length=10)
    lif_cyc = models.CharField(max_length=10)
    trippurp = models.CharField(max_length=10)
    awayhome = models.CharField(max_length=10)
    cdivmsar = models.CharField(max_length=10)
    census_d = models.CharField(max_length=10)
    census_r = models.CharField(max_length=10)
    drop_prk = models.CharField(max_length=10)
    drvr_flg = models.CharField(max_length=10)
    educ = models.CharField(max_length=10)
    endtime = models.DecimalField(max_digits=65535, decimal_places=65535)
    hh_ontd = models.CharField(max_length=10)
    hhmemdrv = models.CharField(max_length=10)
    hhresp = models.CharField(max_length=10)
    hhstate = models.CharField(max_length=10)
    hhstfips = models.CharField(max_length=10)
    intstate = models.CharField(max_length=10)
    msacat = models.CharField(max_length=10)
    msasize = models.CharField(max_length=10)
    nonhhcnt = models.CharField(max_length=10)
    numontrp = models.CharField(max_length=10)
    paytoll = models.CharField(max_length=10)
    prmact = models.CharField(max_length=10)
    proxy = models.CharField(max_length=10)
    psgr_flg = models.CharField(max_length=10)
    r_age = models.CharField(max_length=10)
    rail = models.CharField(max_length=10)
    strttime = models.DecimalField(max_digits=65535, decimal_places=65535)
    tracc1 = models.CharField(max_length=10)
    tracc2 = models.CharField(max_length=10)
    tracc3 = models.CharField(max_length=10)
    tracc4 = models.CharField(max_length=10)
    tracc5 = models.CharField(max_length=10)
    tracctm = models.CharField(max_length=10)
    travday = models.CharField(max_length=10)
    tregr1 = models.CharField(max_length=10)
    tregr2 = models.CharField(max_length=10)
    tregr3 = models.CharField(max_length=10)
    tregr4 = models.CharField(max_length=10)
    tregr5 = models.CharField(max_length=10)
    tregrtm = models.CharField(max_length=10)
    trpaccmp = models.CharField(max_length=10)
    trphhacc = models.CharField(max_length=10)
    trphhveh = models.CharField(max_length=10)
    trptrans = models.CharField(max_length=10)
    trvl_min = models.DecimalField(max_digits=65535, decimal_places=65535)
    trvlcmin = models.DecimalField(max_digits=65535, decimal_places=65535)
    trwaittm = models.CharField(max_length=10)
    urban = models.CharField(max_length=10)
    urbansize = models.CharField(max_length=10)
    urbrur = models.CharField(max_length=10)
    useintst = models.CharField(max_length=10)
    usepubtr = models.CharField(max_length=10)
    vehid = models.CharField(max_length=10)
    whodrove = models.CharField(max_length=10)
    whyfrom = models.CharField(max_length=10)
    whyto = models.CharField(max_length=10)
    whytrp1s = models.CharField(max_length=10)
    wrkcount = models.CharField(max_length=10)
    dweltime = models.CharField(max_length=10)
    whytrp90 = models.CharField(max_length=10)
    tdtrpnum = models.CharField(max_length=10)
    tdwknd = models.CharField(max_length=10)
    tdaydate = models.CharField(max_length=10)
    trpmiles = models.DecimalField(max_digits=65535, decimal_places=65535)
    wttrdfin = models.DecimalField(max_digits=65535, decimal_places=65535)
    vmt_mile = models.CharField(max_length=50)
    pubtrans = models.CharField(max_length=10)
    homeown = models.CharField(max_length=10)
    hometype = models.CharField(max_length=10)
    hbhur = models.CharField(max_length=10)
    htresdn = models.CharField(max_length=10)
    hthtnrnt = models.CharField(max_length=10)
    htppopdn = models.CharField(max_length=10)
    hteempdn = models.CharField(max_length=10)
    hbresdn = models.CharField(max_length=10)
    hbhtnrnt = models.CharField(max_length=10)
    hbppopdn = models.CharField(max_length=10)
    gasprice = models.CharField(max_length=10)
    vehtype = models.CharField(max_length=10)
    hh_cbsa = models.CharField(max_length=10)
    hhc_msa = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'dayv2pub'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Hhpub(models.Model):
    houseid = models.CharField(primary_key=True, max_length=20)
    travday = models.IntegerField(blank=True, null=True)
    sampstrat = models.IntegerField(blank=True, null=True)
    homeown = models.IntegerField(blank=True, null=True)
    hhsize = models.IntegerField(blank=True, null=True)
    hhvehcnt = models.IntegerField(blank=True, null=True)
    hhfaminc = models.IntegerField(blank=True, null=True)
    pc = models.IntegerField(blank=True, null=True)
    sphone = models.IntegerField(blank=True, null=True)
    tab = models.IntegerField(blank=True, null=True)
    walk = models.IntegerField(blank=True, null=True)
    bike = models.IntegerField(blank=True, null=True)
    car = models.IntegerField(blank=True, null=True)
    taxi = models.IntegerField(blank=True, null=True)
    bus = models.IntegerField(blank=True, null=True)
    train = models.IntegerField(blank=True, null=True)
    para = models.IntegerField(blank=True, null=True)
    price = models.IntegerField(blank=True, null=True)
    place = models.IntegerField(blank=True, null=True)
    walk2save = models.IntegerField(blank=True, null=True)
    bike2save = models.IntegerField(blank=True, null=True)
    ptrans = models.IntegerField(blank=True, null=True)
    hhrelatd = models.IntegerField(blank=True, null=True)
    drvrcnt = models.IntegerField(blank=True, null=True)
    cnttdhh = models.IntegerField(blank=True, null=True)
    hhstate = models.CharField(max_length=10, blank=True, null=True)
    hhstfips = models.IntegerField(blank=True, null=True)
    numadlt = models.IntegerField(blank=True, null=True)
    youngchild = models.IntegerField(blank=True, null=True)
    wrkcount = models.IntegerField(blank=True, null=True)
    tdaydate = models.IntegerField(blank=True, null=True)
    hhresp = models.IntegerField(blank=True, null=True)
    lif_cyc = models.IntegerField(blank=True, null=True)
    msacat = models.IntegerField(blank=True, null=True)
    msasize = models.IntegerField(blank=True, null=True)
    rail = models.IntegerField(blank=True, null=True)
    urban = models.IntegerField(blank=True, null=True)
    urbansize = models.IntegerField(blank=True, null=True)
    urbrur = models.IntegerField(blank=True, null=True)
    scresp = models.IntegerField(blank=True, null=True)
    census_d = models.IntegerField(blank=True, null=True)
    census_r = models.IntegerField(blank=True, null=True)
    cdivmsar = models.IntegerField(blank=True, null=True)
    hh_race = models.IntegerField(blank=True, null=True)
    hh_hisp = models.IntegerField(blank=True, null=True)
    hh_cbsa = models.CharField(max_length=20, blank=True, null=True)
    resp_cnt = models.IntegerField(blank=True, null=True)
    hbhtnrnt = models.IntegerField(blank=True, null=True)
    hbppopdn = models.IntegerField(blank=True, null=True)
    hbresdn = models.IntegerField(blank=True, null=True)
    hteempdn = models.IntegerField(blank=True, null=True)
    hthtnrnt = models.IntegerField(blank=True, null=True)
    htppopdn = models.IntegerField(blank=True, null=True)
    htresdn = models.IntegerField(blank=True, null=True)
    webuse17 = models.IntegerField(blank=True, null=True)
    smplsrce = models.IntegerField(blank=True, null=True)
    wthhfin = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'hhpub'


class Hhv2Pub(models.Model):
    houseid = models.CharField(primary_key=True, max_length=20)
    varstrat = models.CharField(max_length=10)
    wthhfin = models.CharField(max_length=50)
    drvrcnt = models.CharField(max_length=10)
    cdivmsar = models.CharField(max_length=10)
    census_d = models.CharField(max_length=10)
    census_r = models.CharField(max_length=10)
    hh_hisp = models.CharField(max_length=10)
    hh_race = models.DecimalField(max_digits=65535, decimal_places=65535)
    hhfaminc = models.DecimalField(max_digits=65535, decimal_places=65535)
    hhrelatd = models.CharField(max_length=10)
    hhresp = models.CharField(max_length=10)
    hhsize = models.CharField(max_length=10)
    hhstate = models.CharField(max_length=10)
    hhstfips = models.CharField(max_length=10)
    hhvehcnt = models.CharField(max_length=10)
    homeown = models.CharField(max_length=10)
    hometype = models.CharField(max_length=10)
    msacat = models.CharField(max_length=10)
    msasize = models.CharField(max_length=10)
    numadlt = models.CharField(max_length=10)
    rail = models.CharField(max_length=10)
    resp_cnt = models.CharField(max_length=10)
    scresp = models.CharField(max_length=10)
    travday = models.CharField(max_length=10)
    urban = models.CharField(max_length=10)
    urbansize = models.CharField(max_length=10)
    urbrur = models.CharField(max_length=10)
    wrkcount = models.CharField(max_length=10)
    tdaydate = models.CharField(max_length=10)
    flag100 = models.CharField(max_length=10)
    lif_cyc = models.CharField(max_length=10)
    cnttdhh = models.CharField(max_length=10)
    hbhur = models.CharField(max_length=10)
    htresdn = models.CharField(max_length=10)
    hthtnrnt = models.CharField(max_length=10)
    htppopdn = models.CharField(max_length=10)
    hteempdn = models.CharField(max_length=10)
    hbresdn = models.CharField(max_length=10)
    hbhtnrnt = models.CharField(max_length=10)
    hbppopdn = models.CharField(max_length=10)
    hh_cbsa = models.CharField(max_length=10)
    hhc_msa = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'hhv2pub'


class Perpub(models.Model):
    houseid = models.CharField(max_length=50, blank=True, null=True)
    personid = models.IntegerField(blank=True, null=True)
    r_age = models.IntegerField(blank=True, null=True)
    educ = models.IntegerField(blank=True, null=True)
    r_hisp = models.IntegerField(blank=True, null=True)
    r_relat = models.IntegerField(blank=True, null=True)
    r_sex = models.IntegerField(blank=True, null=True)
    r_race = models.IntegerField(blank=True, null=True)
    prmact = models.IntegerField(blank=True, null=True)
    payprof = models.IntegerField(blank=True, null=True)
    gt1jblwk = models.IntegerField(blank=True, null=True)
    wrk_home = models.IntegerField(blank=True, null=True)
    wkftpt = models.IntegerField(blank=True, null=True)
    wrktrans = models.IntegerField(blank=True, null=True)
    lsttrday17 = models.IntegerField(blank=True, null=True)
    occat = models.IntegerField(blank=True, null=True)
    schtyp = models.IntegerField(blank=True, null=True)
    nwalktrp = models.IntegerField(blank=True, null=True)
    walk4ex = models.IntegerField(blank=True, null=True)
    nbiketrp = models.IntegerField(blank=True, null=True)
    bike4ex = models.IntegerField(blank=True, null=True)
    bikeshare = models.IntegerField(blank=True, null=True)
    ptused = models.IntegerField(blank=True, null=True)
    mcused = models.IntegerField(blank=True, null=True)
    carshare = models.IntegerField(blank=True, null=True)
    rideshare = models.IntegerField(blank=True, null=True)
    carrode = models.IntegerField(blank=True, null=True)
    timetowk = models.IntegerField(blank=True, null=True)
    nocong = models.IntegerField(blank=True, null=True)
    pubtime = models.IntegerField(blank=True, null=True)
    wrktime = models.CharField(max_length=50, blank=True, null=True)
    wkrmhm = models.IntegerField(blank=True, null=True)
    flextime = models.IntegerField(blank=True, null=True)
    wkfmhmxx = models.IntegerField(blank=True, null=True)
    schtrn1 = models.IntegerField(blank=True, null=True)
    schtrn2 = models.IntegerField(blank=True, null=True)
    deliver = models.IntegerField(blank=True, null=True)
    medcond = models.IntegerField(blank=True, null=True)
    medcond6 = models.IntegerField(blank=True, null=True)
    health = models.IntegerField(blank=True, null=True)
    phyact = models.IntegerField(blank=True, null=True)
    vpact = models.IntegerField(blank=True, null=True)
    lpact = models.IntegerField(blank=True, null=True)
    borninus = models.IntegerField(blank=True, null=True)
    yrtous = models.IntegerField(blank=True, null=True)
    yearmile = models.IntegerField(blank=True, null=True)
    proxy = models.IntegerField(blank=True, null=True)
    whoproxy = models.IntegerField(blank=True, null=True)
    usepubtr = models.IntegerField(blank=True, null=True)
    sameplc = models.IntegerField(blank=True, null=True)
    w_none = models.IntegerField(blank=True, null=True)
    w_cane = models.IntegerField(blank=True, null=True)
    w_wlkr = models.IntegerField(blank=True, null=True)
    w_whcane = models.IntegerField(blank=True, null=True)
    w_dog = models.IntegerField(blank=True, null=True)
    w_crutch = models.IntegerField(blank=True, null=True)
    w_scootr = models.IntegerField(blank=True, null=True)
    w_chair = models.IntegerField(blank=True, null=True)
    w_mtrchr = models.IntegerField(blank=True, null=True)
    worker = models.IntegerField(blank=True, null=True)
    diary = models.IntegerField(blank=True, null=True)
    outcntry = models.IntegerField(blank=True, null=True)
    frsthm17 = models.IntegerField(blank=True, null=True)
    cnttdtr = models.IntegerField(blank=True, null=True)
    gcdwork = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    wkstfips = models.IntegerField(blank=True, null=True)
    driver = models.IntegerField(blank=True, null=True)
    outoftwn = models.IntegerField(blank=True, null=True)
    disttowk17 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    disttosc17 = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    alt_16 = models.IntegerField(blank=True, null=True)
    alt_23 = models.IntegerField(blank=True, null=True)
    alt_45 = models.IntegerField(blank=True, null=True)
    walk_def = models.IntegerField(blank=True, null=True)
    walk_gkq = models.IntegerField(blank=True, null=True)
    bike_dfr = models.IntegerField(blank=True, null=True)
    bike_gkp = models.IntegerField(blank=True, null=True)
    condtrav = models.IntegerField(blank=True, null=True)
    condride = models.IntegerField(blank=True, null=True)
    condnigh = models.IntegerField(blank=True, null=True)
    condrive = models.IntegerField(blank=True, null=True)
    condpub = models.IntegerField(blank=True, null=True)
    condspec = models.IntegerField(blank=True, null=True)
    condtax = models.IntegerField(blank=True, null=True)
    travday = models.IntegerField(blank=True, null=True)
    homeown = models.IntegerField(blank=True, null=True)
    hhsize = models.IntegerField(blank=True, null=True)
    hhvehcnt = models.IntegerField(blank=True, null=True)
    hhfaminc = models.IntegerField(blank=True, null=True)
    drvrcnt = models.IntegerField(blank=True, null=True)
    hhstate = models.CharField(max_length=10, blank=True, null=True)
    hhstfips = models.IntegerField(blank=True, null=True)
    numadlt = models.IntegerField(blank=True, null=True)
    wrkcount = models.IntegerField(blank=True, null=True)
    tdaydate = models.IntegerField(blank=True, null=True)
    hhresp = models.IntegerField(blank=True, null=True)
    lif_cyc = models.IntegerField(blank=True, null=True)
    msacat = models.IntegerField(blank=True, null=True)
    msasize = models.IntegerField(blank=True, null=True)
    rail = models.IntegerField(blank=True, null=True)
    urban = models.IntegerField(blank=True, null=True)
    urbansize = models.IntegerField(blank=True, null=True)
    urbrur = models.IntegerField(blank=True, null=True)
    census_d = models.IntegerField(blank=True, null=True)
    census_r = models.IntegerField(blank=True, null=True)
    cdivmsar = models.IntegerField(blank=True, null=True)
    hh_race = models.IntegerField(blank=True, null=True)
    hh_hisp = models.IntegerField(blank=True, null=True)
    hh_cbsa = models.CharField(max_length=50, blank=True, null=True)
    hbhtnrnt = models.IntegerField(blank=True, null=True)
    hbppopdn = models.IntegerField(blank=True, null=True)
    hbresdn = models.IntegerField(blank=True, null=True)
    hteempdn = models.IntegerField(blank=True, null=True)
    hthtnrnt = models.IntegerField(blank=True, null=True)
    htppopdn = models.IntegerField(blank=True, null=True)
    htresdn = models.IntegerField(blank=True, null=True)
    smplsrce = models.IntegerField(blank=True, null=True)
    wtperfin = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'perpub'


class Perv2Pub(models.Model):
    houseid = models.CharField(max_length=20)
    personid = models.CharField(primary_key=True, max_length=50)
    varstrat = models.CharField(max_length=10)
    wtperfin = models.CharField(max_length=50)
    sfwgt = models.CharField(max_length=50)
    hh_hisp = models.CharField(max_length=10)
    hh_race = models.CharField(max_length=10)
    drvrcnt = models.CharField(max_length=10)
    hhfaminc = models.CharField(max_length=10)
    hhsize = models.CharField(max_length=10)
    hhvehcnt = models.CharField(max_length=10)
    numadlt = models.CharField(max_length=10)
    wrkcount = models.CharField(max_length=10)
    flag100 = models.CharField(max_length=10)
    lif_cyc = models.CharField(max_length=10)
    cnttdtr = models.CharField(max_length=10)
    borninus = models.CharField(max_length=10)
    carrode = models.CharField(max_length=10)
    cdivmsar = models.CharField(max_length=10)
    census_d = models.CharField(max_length=10)
    census_r = models.CharField(max_length=10)
    condnigh = models.CharField(max_length=10)
    condpub = models.CharField(max_length=10)
    condride = models.CharField(max_length=10)
    condrive = models.CharField(max_length=10)
    condspec = models.CharField(max_length=10)
    condtax = models.CharField(max_length=10)
    condtrav = models.CharField(max_length=10)
    deliver = models.CharField(max_length=10)
    diary = models.CharField(max_length=10)
    disttosc = models.CharField(max_length=10)
    driver = models.CharField(max_length=10)
    dtacdt = models.CharField(max_length=10)
    dtconj = models.CharField(max_length=10)
    dtcost = models.CharField(max_length=10)
    dtrage = models.CharField(max_length=10)
    dtran = models.CharField(max_length=10)
    dtwalk = models.CharField(max_length=10)
    educ = models.CharField(max_length=10)
    everdrov = models.CharField(max_length=10)
    flextime = models.CharField(max_length=10)
    fmscsize = models.CharField(max_length=10)
    frsthm = models.CharField(max_length=10)
    fxdwkpl = models.CharField(max_length=10)
    gcdwork = models.CharField(max_length=20)
    grade = models.CharField(max_length=10)
    gt1jblwk = models.CharField(max_length=10)
    hhresp = models.CharField(max_length=10)
    hhstate = models.CharField(max_length=10)
    hhstfips = models.CharField(max_length=10)
    issue = models.CharField(max_length=10)
    occat = models.CharField(max_length=10)
    lsttrday = models.CharField(max_length=10)
    mcused = models.CharField(max_length=10)
    medcond = models.CharField(max_length=10)
    medcond6 = models.CharField(max_length=10)
    moroften = models.CharField(max_length=10)
    msacat = models.CharField(max_length=10)
    msasize = models.CharField(max_length=10)
    nbiketrp = models.CharField(max_length=10)
    nwalktrp = models.CharField(max_length=10)
    outcntry = models.CharField(max_length=10)
    outoftwn = models.CharField(max_length=10)
    payprof = models.CharField(max_length=10)
    prmact = models.CharField(max_length=10)
    proxy = models.CharField(max_length=10)
    ptused = models.CharField(max_length=10)
    purchase = models.CharField(max_length=10)
    r_age = models.CharField(max_length=10)
    r_relat = models.CharField(max_length=10)
    r_sex = models.CharField(max_length=10)
    rail = models.CharField(max_length=10)
    sameplc = models.CharField(max_length=10)
    schcare = models.CharField(max_length=10)
    schcrim = models.CharField(max_length=10)
    schdist = models.CharField(max_length=10)
    schspd = models.CharField(max_length=10)
    schtraf = models.CharField(max_length=10)
    schtrn1 = models.CharField(max_length=10)
    schtrn2 = models.CharField(max_length=10)
    schtyp = models.CharField(max_length=10)
    schwthr = models.CharField(max_length=10)
    self_emp = models.CharField(max_length=10)
    timetosc = models.CharField(max_length=10)
    timetowk = models.CharField(max_length=10)
    toscsize = models.CharField(max_length=10)
    travday = models.CharField(max_length=10)
    urban = models.CharField(max_length=10)
    urbansize = models.CharField(max_length=10)
    urbrur = models.CharField(max_length=10)
    useintst = models.CharField(max_length=10)
    usepubtr = models.CharField(max_length=10)
    webuse = models.CharField(max_length=10)
    wkfmhmxx = models.CharField(max_length=10)
    wkftpt = models.CharField(max_length=10)
    wkrmhm = models.CharField(max_length=10)
    wkstfips = models.CharField(max_length=10)
    worker = models.CharField(max_length=10)
    wrktime = models.CharField(max_length=10)
    wrktrans = models.CharField(max_length=10)
    yearmile = models.CharField(max_length=10)
    yrmlcap = models.CharField(max_length=10)
    yrtous = models.CharField(max_length=10)
    disttowk = models.CharField(max_length=10)
    tdaydate = models.CharField(max_length=15)
    homeown = models.CharField(max_length=10)
    hometype = models.CharField(max_length=10)
    hbhur = models.CharField(max_length=5)
    htresdn = models.CharField(max_length=10)
    hthtnrnt = models.CharField(max_length=10)
    htppopdn = models.CharField(max_length=10)
    hteempdn = models.CharField(max_length=10)
    hbresdn = models.CharField(max_length=10)
    hbhtnrnt = models.CharField(max_length=10)
    hbppopdn = models.CharField(max_length=10)
    hh_cbsa = models.CharField(max_length=10)
    hhc_msa = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'perv2pub'
        unique_together = (('personid', 'houseid'),)


class Trippub(models.Model):
    houseid = models.CharField(max_length=50, blank=True, null=True)
    personid = models.IntegerField(blank=True, null=True)
    tdtrpnum = models.IntegerField(blank=True, null=True)
    strttime = models.IntegerField(blank=True, null=True)
    endtime = models.IntegerField(blank=True, null=True)
    trvlcmin = models.IntegerField(blank=True, null=True)
    trpmiles = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    trptrans = models.IntegerField(blank=True, null=True)
    trpaccmp = models.IntegerField(blank=True, null=True)
    trphhacc = models.IntegerField(blank=True, null=True)
    vehid = models.IntegerField(blank=True, null=True)
    trwaittm = models.IntegerField(blank=True, null=True)
    numtrans = models.IntegerField(blank=True, null=True)
    tracctm = models.IntegerField(blank=True, null=True)
    drop_prk = models.IntegerField(blank=True, null=True)
    tregrtm = models.IntegerField(blank=True, null=True)
    whodrove = models.IntegerField(blank=True, null=True)
    whyfrom = models.IntegerField(blank=True, null=True)
    loop_trip = models.IntegerField(blank=True, null=True)
    trphhveh = models.IntegerField(blank=True, null=True)
    hhmemdrv = models.IntegerField(blank=True, null=True)
    hh_ontd = models.IntegerField(blank=True, null=True)
    nonhhcnt = models.IntegerField(blank=True, null=True)
    numontrp = models.IntegerField(blank=True, null=True)
    psgr_flg = models.IntegerField(blank=True, null=True)
    pubtrans = models.IntegerField(blank=True, null=True)
    trippurp = models.CharField(max_length=50, blank=True, null=True)
    dweltime = models.IntegerField(blank=True, null=True)
    tdwknd = models.IntegerField(blank=True, null=True)
    vmt_mile = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    drvr_flg = models.IntegerField(blank=True, null=True)
    whytrp1s = models.IntegerField(blank=True, null=True)
    whytrp90 = models.IntegerField(blank=True, null=True)
    ontd_p1 = models.IntegerField(blank=True, null=True)
    ontd_p2 = models.IntegerField(blank=True, null=True)
    ontd_p3 = models.IntegerField(blank=True, null=True)
    ontd_p4 = models.IntegerField(blank=True, null=True)
    ontd_p5 = models.IntegerField(blank=True, null=True)
    ontd_p6 = models.IntegerField(blank=True, null=True)
    ontd_p7 = models.IntegerField(blank=True, null=True)
    ontd_p8 = models.IntegerField(blank=True, null=True)
    ontd_p9 = models.IntegerField(blank=True, null=True)
    ontd_p10 = models.IntegerField(blank=True, null=True)
    ontd_p11 = models.IntegerField(blank=True, null=True)
    ontd_p12 = models.IntegerField(blank=True, null=True)
    ontd_p13 = models.IntegerField(blank=True, null=True)
    tdcaseid = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    tracc_wlk = models.IntegerField(blank=True, null=True)
    tracc_pov = models.IntegerField(blank=True, null=True)
    tracc_bus = models.IntegerField(blank=True, null=True)
    tracc_crl = models.IntegerField(blank=True, null=True)
    tracc_sub = models.IntegerField(blank=True, null=True)
    tracc_oth = models.IntegerField(blank=True, null=True)
    tregr_wlk = models.IntegerField(blank=True, null=True)
    tregr_pov = models.IntegerField(blank=True, null=True)
    tregr_bus = models.IntegerField(blank=True, null=True)
    tregr_crl = models.IntegerField(blank=True, null=True)
    tregr_sub = models.IntegerField(blank=True, null=True)
    tregr_oth = models.IntegerField(blank=True, null=True)
    whyto = models.IntegerField(blank=True, null=True)
    travday = models.IntegerField(blank=True, null=True)
    homeown = models.IntegerField(blank=True, null=True)
    hhsize = models.IntegerField(blank=True, null=True)
    hhvehcnt = models.IntegerField(blank=True, null=True)
    hhfaminc = models.IntegerField(blank=True, null=True)
    drvrcnt = models.IntegerField(blank=True, null=True)
    hhstate = models.CharField(max_length=50, blank=True, null=True)
    hhstfips = models.IntegerField(blank=True, null=True)
    numadlt = models.IntegerField(blank=True, null=True)
    wrkcount = models.IntegerField(blank=True, null=True)
    tdaydate = models.IntegerField(blank=True, null=True)
    hhresp = models.IntegerField(blank=True, null=True)
    lif_cyc = models.IntegerField(blank=True, null=True)
    msacat = models.IntegerField(blank=True, null=True)
    msasize = models.IntegerField(blank=True, null=True)
    rail = models.IntegerField(blank=True, null=True)
    urban = models.IntegerField(blank=True, null=True)
    urbansize = models.IntegerField(blank=True, null=True)
    urbrur = models.IntegerField(blank=True, null=True)
    gasprice = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    census_d = models.IntegerField(blank=True, null=True)
    census_r = models.IntegerField(blank=True, null=True)
    cdivmsar = models.IntegerField(blank=True, null=True)
    hh_race = models.IntegerField(blank=True, null=True)
    hh_hisp = models.IntegerField(blank=True, null=True)
    hh_cbsa = models.CharField(max_length=50, blank=True, null=True)
    hbhtnrnt = models.IntegerField(blank=True, null=True)
    hbppopdn = models.IntegerField(blank=True, null=True)
    hbresdn = models.IntegerField(blank=True, null=True)
    hteempdn = models.IntegerField(blank=True, null=True)
    hthtnrnt = models.IntegerField(blank=True, null=True)
    htppopdn = models.IntegerField(blank=True, null=True)
    htresdn = models.IntegerField(blank=True, null=True)
    smplsrce = models.IntegerField(blank=True, null=True)
    r_age = models.IntegerField(blank=True, null=True)
    educ = models.IntegerField(blank=True, null=True)
    r_sex = models.IntegerField(blank=True, null=True)
    prmact = models.IntegerField(blank=True, null=True)
    proxy = models.IntegerField(blank=True, null=True)
    worker = models.IntegerField(blank=True, null=True)
    driver = models.IntegerField(blank=True, null=True)
    wttrdfin = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'trippub'


class Vehpub(models.Model):
    houseid = models.CharField(max_length=20, blank=True, null=True)
    vehid = models.IntegerField(blank=True, null=True)
    vehyear = models.IntegerField(blank=True, null=True)
    vehage = models.IntegerField(blank=True, null=True)
    make = models.CharField(max_length=50, blank=True, null=True)
    model = models.CharField(max_length=50, blank=True, null=True)
    fueltype = models.IntegerField(blank=True, null=True)
    vehtype = models.IntegerField(blank=True, null=True)
    whomain = models.IntegerField(blank=True, null=True)
    od_read = models.IntegerField(blank=True, null=True)
    hfuel = models.IntegerField(blank=True, null=True)
    vehowned = models.IntegerField(blank=True, null=True)
    vehownmo = models.IntegerField(blank=True, null=True)
    annmiles = models.IntegerField(blank=True, null=True)
    hybrid = models.IntegerField(blank=True, null=True)
    personid = models.IntegerField(blank=True, null=True)
    travday = models.IntegerField(blank=True, null=True)
    homeown = models.IntegerField(blank=True, null=True)
    hhsize = models.IntegerField(blank=True, null=True)
    hhvehcnt = models.IntegerField(blank=True, null=True)
    hhfaminc = models.IntegerField(blank=True, null=True)
    drvrcnt = models.IntegerField(blank=True, null=True)
    hhstate = models.CharField(max_length=10, blank=True, null=True)
    hhstfips = models.IntegerField(blank=True, null=True)
    numadlt = models.IntegerField(blank=True, null=True)
    wrkcount = models.IntegerField(blank=True, null=True)
    tdaydate = models.IntegerField(blank=True, null=True)
    lif_cyc = models.IntegerField(blank=True, null=True)
    msacat = models.IntegerField(blank=True, null=True)
    msasize = models.IntegerField(blank=True, null=True)
    rail = models.IntegerField(blank=True, null=True)
    urban = models.IntegerField(blank=True, null=True)
    urbansize = models.IntegerField(blank=True, null=True)
    urbrur = models.IntegerField(blank=True, null=True)
    census_d = models.IntegerField(blank=True, null=True)
    census_r = models.IntegerField(blank=True, null=True)
    cdivmsar = models.IntegerField(blank=True, null=True)
    hh_race = models.IntegerField(blank=True, null=True)
    hh_hisp = models.IntegerField(blank=True, null=True)
    hh_cbsa = models.CharField(max_length=50, blank=True, null=True)
    hbhtnrnt = models.IntegerField(blank=True, null=True)
    hbppopdn = models.IntegerField(blank=True, null=True)
    hbresdn = models.IntegerField(blank=True, null=True)
    hteempdn = models.IntegerField(blank=True, null=True)
    hthtnrnt = models.IntegerField(blank=True, null=True)
    htppopdn = models.IntegerField(blank=True, null=True)
    htresdn = models.IntegerField(blank=True, null=True)
    smplsrce = models.IntegerField(blank=True, null=True)
    wthhfin = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'vehpub'


class Vehv2Pub(models.Model):
    houseid = models.CharField(primary_key=True, max_length=20)
    wthhfin = models.CharField(max_length=50)
    vehid = models.CharField(max_length=10)
    drvrcnt = models.CharField(max_length=10)
    hhfaminc = models.CharField(max_length=10)
    hhsize = models.CharField(max_length=10)
    hhvehcnt = models.CharField(max_length=10)
    numadlt = models.CharField(max_length=10)
    flag100 = models.CharField(max_length=10)
    cdivmsar = models.CharField(max_length=10)
    census_d = models.CharField(max_length=10)
    census_r = models.CharField(max_length=10)
    hhstate = models.CharField(max_length=10)
    hhstfips = models.CharField(max_length=10)
    hybrid = models.CharField(max_length=10)
    makecode = models.CharField(max_length=10)
    modlcode = models.CharField(max_length=10)
    msacat = models.CharField(max_length=10)
    msasize = models.CharField(max_length=10)
    od_read = models.CharField(max_length=10)
    rail = models.CharField(max_length=10)
    travday = models.CharField(max_length=10)
    urban = models.CharField(max_length=10)
    urbansize = models.CharField(max_length=10)
    urbrur = models.CharField(max_length=10)
    vehcomm = models.CharField(max_length=10)
    vehownmo = models.CharField(max_length=50)
    vehyear = models.CharField(max_length=10)
    whomain = models.CharField(max_length=10)
    wrkcount = models.CharField(max_length=10)
    tdaydate = models.CharField(max_length=15)
    vehage = models.CharField(max_length=10)
    personid = models.CharField(max_length=10)
    hh_hisp = models.CharField(max_length=10)
    hh_race = models.CharField(max_length=10)
    homeown = models.CharField(max_length=10)
    hometype = models.CharField(max_length=10)
    lif_cyc = models.CharField(max_length=10)
    annmiles = models.CharField(max_length=50)
    hbhur = models.CharField(max_length=10)
    htresdn = models.CharField(max_length=10)
    hthtnrnt = models.CharField(max_length=10)
    htppopdn = models.CharField(max_length=10)
    hteempdn = models.CharField(max_length=10)
    hbresdn = models.CharField(max_length=10)
    hbhtnrnt = models.CharField(max_length=10)
    hbppopdn = models.CharField(max_length=10)
    best_flg = models.CharField(max_length=10)
    bestmile = models.CharField(max_length=20)
    best_edt = models.CharField(max_length=10)
    best_out = models.CharField(max_length=10)
    fueltype = models.CharField(max_length=10)
    gsyrgal = models.CharField(max_length=10)
    gscost = models.DecimalField(max_digits=65535, decimal_places=65535)
    gstotcst = models.CharField(max_length=10)
    epatmpg = models.CharField(max_length=50)
    epatmpgf = models.CharField(max_length=10)
    eiadmpg = models.CharField(max_length=10)
    vehtype = models.CharField(max_length=10)
    hh_cbsa = models.CharField(max_length=10)
    hhc_msa = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'vehv2pub'
        unique_together = (('houseid', 'vehid'),)
